### ISSUE TITLE
Bundle gem error for Shopify latest version 7.0.1

### ISSUE THREAD

**Issue by vjraw** [mikeyhew/shopify_graphql_client#1]
Hi,

I am not able to successfully run bundle. I am getting below error while adding gem. 

Bundler could not find compatible versions for gem "shopify_api":
shopify_graphql_client was resolved to 0.2.0, which depends on
      shopify_api (>= 5.2, < 7.0)

Please update this gem to support shopify api latest version.

Thanks

**Comment by mikeyhew** [comment]
Hi @vjraw, thanks for opening this issue. I'll push some code to remove the upper bound on the version for `shopify_api`, since it likely won't change in any way that will break this code.
