### ISSUE TITLE
Bundle gem error: Could not find a valid gem 'shopify_graphql_client'

### ISSUE THREAD

**Issue by joesideas** [mikeyhew/shopify_graphql_client#3]
When trying to install the gem I get this error: 
ERROR:  Could not find a valid gem 'shopify_graphql_client' (>= 0) in any repository
ERROR:  Possible alternatives: shopify-graphql_proxy, graphql-client, graphql_client, github-graphql-client, shopify_client

Is this gem no longer in use?

**Comment by mikeyhew** [comment]
Oh sorry, this isn't on rubygems so you'll have to put this in your Gemfile:

```ruby
gem 'shopify_graphql_client', githhub: 'mikeyhew/shopify_graphql_client`
```

The documentation on this in the Readme is auto-generated by bundler and is wrong.

**Comment by joesideas** [comment]
You the man. I set it up and it works great, solved the memory issue I was facing. Thanks for creating this 👍
